/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/Rocket.glb
Author: Rain (https://sketchfab.com/rainfab)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rocket-53ce2cc1530f43afad208305f921b67f
Title: Rocket
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
export function Rocket(props) {
  const { nodes, materials } = useGLTF("./models/Rocket.glb");
  const rocketRef = useRef();

  useFrame(() => {
    rocketRef.current.rotation.y += 0.02;
    rocketRef.current.position.z =
      (Math.sin(Date.now() * 0.001) * window.innerWidth - 4000) / 1000;
    // (Math.sin(Date.now() * 0.001) * window.innerWidth - 1000) / 100;
  });

  return (
    <group
      rotation={[90 * (Math.PI / 180), 0, 0]}
      position-x={-5}
      position-y={-1}
      // position={[-5, 0, 0]}
      scale={[0.1, 0.1, 0.1]}
      ref={rocketRef}
      {...props}
      dispose={null}
    >
      <mesh geometry={nodes.Object_4.geometry} material={materials.phong2SG} />
      <mesh geometry={nodes.Object_5.geometry} material={materials.blinn1SG} />
      <mesh geometry={nodes.Object_6.geometry} material={materials.blinn2SG} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.blinn3SG} />
      <mesh geometry={nodes.Object_8.geometry} material={materials.phong1SG} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.blinn5SG} />
    </group>
  );
}

useGLTF.preload("./models/Rocket.glb");
